version: "3"

services:
  app:
    build: .
    container_name: ignite-timer
    ports:
      - "3000:5173"
    volumes:
      - .:/app
    command:
      - /bin/sh
      - -c
      - | 
        yarn 
        yarn dev --host